Alors en fait, le seul principe de cette page, c'est qu'elle se rafraîchi tout le temps. 😅
Sauf que tu as trouvé le truc. 😮 Tu as appuyer sur la petite croix ! Ouaaaaaaaiiiiiiiis ! 😂
La page a arrêté de se rafraîchir. Tu as cliquer sur "what what what what" et tu es ensuite arrivé ici... 😶
